[colors.primary]
background = '#17120f'
foreground = '#ece0da'
 
[colors.cursor]
text = '#ece0da'
cursor = '#d6c3b6' 
 
[colors.vi_mode_cursor]
text = '#17120f'
cursor = '#ffb778' 
 
[colors.search.matches]
foreground = '#51443a' 
background = '#c3cb98' 
 
[colors.search.focused_match]
foreground = '#51443a' 
background = '#ffb778' 
 
[colors.footer_bar]
foreground = '#51443a' 
background = '#ece0da' 
 
[colors.hints.start]
foreground = '#51443a' 
background = '#e2c0a5' 
 
[colors.hints.end]
foreground = '#51443a' 
background = '#e2c0a5' 
 
[colors.selection]
text = '#17120f'
background = '#ffb778'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ffb778' 
yellow = '#8e4e00' 
blue = '#ffb778' 
magenta = '#c3cb98' 
cyan = '#e2c0a5' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 