[manager]
show_hidden = true
sort_by = "natural"

[opener]
edit = [
    { run = 'nvim "$@"', block = true, desc = "Edit in Neovim" }
]

[open]
rules = [
    { name = "*.txt", mime = "*", use = "edit" },
    { name = "*.nix", mime = "*", use = "edit" },
    { name = "*.conf", mime = "*", use = "edit" },
    { name = "*.lua", mime = "*", use = "edit" },
    { name = "*.md", mime = "*", use = "edit" },
    { name = "*.sh", mime = "*", use = "edit" },
    # Fallback for all other files
    { mime = "*", use = "edit" }
]
